export const annoucements = [
  {
    id: 0,
    subject: "Eid Mubarak",
    image: '2021EidPrayer.png',
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "",
    hrefURL: "",
    email: "",
    telephone: "",
    tag: "#Eid"
  },
  {
    id: 1,
    subject: "Get Your Covid-19 Vaccine",
    image: 'vaccines.jpg',
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "",
    hrefURL: "http://isak.org/vaccine",
    email: "info@isak.org",
    telephone: "",
    tag: "#COVID",
  },
  {
    id: 2,
    subject: "Covid Vaccine - 2nd Shot, 16 yrs old and up",
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "Please register through the link to receive your Pfizer vaccine for April 17th. The 2nd appointment will be booked on site when you arrive for your first dose.",
    hrefURL: "https://cuyahogadose141792.timetap.com/" ,
    email: "",
    telephone: "",
    tag:"#COVID",
  },
  {
    id: 3,
    subject: "Power of Truth vs The Danger of the Lie",
    image: 'powerOfTruth.jpg',
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "",
    hrefURL: "",
    email: "",
    telephone: "",
    tag: "#Conversations",
  },
  {
    id: 4,
    subject: "Cleveland Muslim Volunteer",
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "Cleveland Muslim Volunteers has been formed to serve the elderly, sick, and underprivileged individuals and families during the COVID-19 pandemic in the Greater Cleveland Area",
    hrefURL: "https://clevelandmuslimvolunteers.com/" ,
    email: "",
    telephone: "",
    tag: "#ClevelandMuslimVolunteer"
  },
  {
    id: 5,
    subject: "Ramadan Kareem",
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "The first day of fast is on April 13th. The 1st reading of the Qur'an will start at 7:10p, live streamed, on April 12th until 8:13p, in sha Allah. Taraweeh prayers will be held immediately after isha prayer. Isha starts at 9:15p.",
    hrefURL: "" ,
    email: "",
    telephone: "",
    tag:"#Ramadan",
  },
  
  
  {
    id: 99,
    subject: "Seeking Talented Individuals",
    image: "",
    greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
    body: "The First Cleveland Mosque's devops admin is looking for individuals to help propagate the message of Islam through technology. You must be dedicated, have an open mind, and the willingness to learn. Drop us a line with a subject line of (to know you're serious): DevOps Department",
    hrefURL: "",
    email: "1stclevelandmosque@gmail.com",
    telephone: "",
    tag: "#SeekingTalent"
  },
]