export const annoucements = [
    {
        id: 0,
        subject: "Seeking Talented Individuals",
        image: "",
        greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
        body: "The First Cleveland Mosque's devops admin is looking for individuals to help propagate the message of Islam through technology. You must be dedicated, have an open mind, and the willingness to learn. Drop us a line with a subject line of (to know you're serious): DevOps Department",
        hrefURL: "",
        email: "1stclevelandmosque@gmail.com",
        telephone: "",
    },
    {
        id: 1,
        subject: "Cleveland Muslim Volunteer",
        image: "",
        greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
        body: "Cleveland Muslim Volunteers has been formed to serve the elderly, sick, and underprivileged individuals and families during the COVID-19 pandemic in the Greater Cleveland Area",
        hrefURL: "https://clevelandmuslimvolunteers.com/" ,
        email: "",
        telephone: "",
      },
      {
        id: 2,
        subject: "Power of Truth vs The Danger of the Lie",
        image: require('../images/powerOfTruth.jpg').default,
        greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
        body: "",
        hrefURL: "",
        email: "",
        telephone: "",
      },
      {
        id: 2,
        subject: "Get Your Covid-19 Vaccine",
        image: require('../images/vaccines.jpg').default,
        greeting: "As-Salamu Aalikum, ٱلسَّلَامُ عَلَيْكُمْ‎",
        body: "",
        hrefURL: "http://isak.org/vaccine",
        email: "info@isak.org",
        telephone: "",
      }
]